---
title: "A single or pooled cutoff?"
date: '2021-02-16'
output: 
  blogdown::html_document2:
    toc: TRUE
    toc_float: TRUE
    toc_depth: 3
bibliography: '../../references-ks.bib'
math: true
---

## Single Cutoff
At its simplest, the RD design exploits an exogenously determined cutoff to assign observations to treatment based on an underlying metric.  If this is true in your context---meaning that you have a single running variable and one cutoff that determines treatment---then you're ready to move on to [Step 2](/rd/step2_overview).

## Pooled Cutoff
If instead, your context has a single running variable with multiple cutoffs to determine treatment, you have a choice to make.  Your first option is to pool the observations by normalizing the running variable for each observation by the relevant cutoff and then proceeding as if there was only one cutoff at $c=0$.  In this way, you now have a single cutoff and can again move on to estimation.  However, this "normalizing-and-pooling" approach will have important implications for the interpretation of the coefficient on treatment that differ from the standard single-cutoff RD design [@cattaneo2016politics].  We'll return to this discussion when we cover the RD [specification](/rd/step2_specification), but be cognizant that this is something you'll need to consider in your discussion of the results.  

You may also choose not to pool your observations and instead analyze separately by cutoff.  We discuss this option more [here](/rd/step1b_mult).  As you conduct your analysis, you can try both pooled and separate analyses, but keep in mind how the interpretation of your result may differ as you vary your specification. 

# References